services:
  asr:
    image: soar97/triton-whisper:24.05-0.1.0
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    environment:
      - PYTHONIOENCODING=utf-8
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    command: >
      /bin/bash -c "ln -sf engines/phowhisper-medium-finetuned/ triton/whisper/model_repo_whisper_tllm/phowhisper_medium_finetuned/1/ && bash triton/whisper/launch_server.sh"